[project]
authors = ["tobias fenner <toby@makerain.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ekf-sim"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "*"
matplotlib = "*"
